version: '3.8'

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: familyhub_db
      POSTGRES_USER: familyhub_user
      POSTGRES_PASSWORD: TempPass123!ChangeMe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U familyhub_user -d familyhub_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  web:
    build: .
    volumes:
      - ./FamilyHub:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://familyhub_user:TempPass123!ChangeMe@db:5432/familyhub_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
