services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  familyhub:
    build: 
      context: .
      dockerfile: FamilyHub/Dockerfile
    volumes:
      - ./FamilyHub:/app/FamilyHub
      - ./standalone-apps:/standalone-apps
      - ./shared:/app/shared
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=FamilyHub.settings.docker
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "cd /app/FamilyHub && 
             python manage.py migrate --noinput && 
             python manage.py collectstatic --noinput && 
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
    driver: local
