version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:17.6
    container_name: familyhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: familyhub
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - familyhub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d familyhub"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Caching and Celery
  redis:
    image: redis:7-alpine
    container_name: familyhub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - familyhub_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: familyhub-web
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./FamilyHub:/app
      - ./requirements:/requirements
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://django_user:your_secure_password@db:5432/familyhub
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - familyhub_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: familyhub-celery
    restart: unless-stopped
    command: celery -A FamilyHub worker --loglevel=info
    volumes:
      - ./FamilyHub:/app
      - ./requirements:/requirements
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://django_user:your_secure_password@db:5432/familyhub
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - familyhub_network

  # Celery Beat Scheduler
  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: familyhub-celery-beat
    restart: unless-stopped
    command: celery -A FamilyHub beat --loglevel=info
    volumes:
      - ./FamilyHub:/app
      - ./requirements:/requirements
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://django_user:your_secure_password@db:5432/familyhub
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - familyhub_network

# Named Volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# Networks
networks:
  familyhub_network:
    driver: bridge
